baseURL = 'https://heidiskockklub.com'
languageCode = 'en-us'
title = 'Heidis Kock Klub'
theme = 'ananke'
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/Moorlag"
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'recipes'
    pageRef = '/recipes'
    weight = 20
[[menus.main]]
    name = 'Issue or problem?'
    pageRef = 'a href ="https://github.com/moorlag/kock/issues"'
    weight = 30
[[menus.main]]
    name = 'Contact'
    pageRef = 'https://www.linkedin.com/in/moorlag/'
    weight = 100