baseURL = 'https://heidiskockklub.com'
languageCode = 'en-us'
title = 'Heidis Kock Klub'
theme = 'ananke'
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'recipes'
    pageRef = '/recipes'
    weight = 20
[[menus.main]]
    name = 'Issue or problem?'
    pageRef = 'https://github.com/moorlag/kock/issues'
    weight = 30
[[menus.main]]
    name = 'Contact'
    pageRef = 'https://www.linkedin.com/in/moorlag/'
    weight = 100