baseURL = 'https://ramonmoorlag.nl/kock/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'recipes'
    pageRef = '/recipes'
    weight = 20
[[menus.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 30